### ISSUE TITLE
=。=！~

### ISSUE THREAD

**Issue by 234369425** [redisson/redisson-examples#10]
使用RList尝试存放对象时，序列化获取的泛型有问题
127.0.0.1:6379>  LRANGE ******** 0 3
1) "{\"@class\":\"************Control$1\",\"endTime\":[\"java.util.Date\",1509093480980],\"numberCount\":5,
\"startTime\":[\"java.util.Date\",1509093480980],\"times\":100}"

**Comment by jackygurui** [comment]
能具体点吗？

**Comment by 234369425** [comment]
抱歉，个人使用问题，有空帮解答下这个弱弱的问题呗，Object o = new Object(){{ this.xxx = xxx,this.yyy=yyy }} 和Object o = new Object();o.setXXX(xxx) 实例化对象有什么区别？

**Comment by jackygurui** [comment]
`Object o = new Object(){{ this.xxx = xxx,this.yyy=yyy }} `表示创建并实例化一个Object之类的匿名类。`Object o = new Object();`表示实例化一个`Object`对象。
