### ISSUE TITLE
Add a Spring session Integration example

### ISSUE THREAD

**Issue by SympathyForTheDev** [redisson/redisson-examples#11]
Hello, 

I have done a sample project for testing the integration with redisson/spring boot/spring session/spring security. (https://github.com/DevWantJustHaveFun/spring-boot-session-redisson)

Do you think it could be useful to add it to this repository ? 

If yes I can make a pull request, if no you can close this issue

**Comment by mrniko** [comment]
Hi,

Thanks for your contribution! Could wait for 3.8.0 version with ready spring boot integration and update your example?

**Comment by SympathyForTheDev** [comment]
Yes  :ok_hand:

**Comment by SympathyForTheDev** [comment]
@mrniko example updated successfully with redisson 3.8.0

**Comment by mrniko** [comment]
@DevWantJustHaveFun 
Thank you!

Why didn't you use spring-boot-starter out of the box?
https://github.com/redisson/redisson/tree/master/redisson-spring-boot-starter#spring-boot-starter

**Comment by SympathyForTheDev** [comment]
@mrniko 
Because,  I was not aware of this, it's a good idea to provide a starter with spring boot auto-configuration and dependencies.

I have tried to use it but i'm stuck with https://github.com/redisson/redisson/issues/1640

**Comment by SympathyForTheDev** [comment]
I do not benefit of the auto-configuration provided by the starter because I use another redis codec (FST), it's probably a good idea to add this point in the configuration (something like: spring.redis.codec=de.ruedigermoeller.fst) thanks

**Comment by mrniko** [comment]
@DevWantJustHaveFun 

You can specify Redisson configuration file through `spring.redis.redisson.config` setting
