### ISSUE TITLE
Error in LockExample.java

### ISSUE THREAD

**Issue by friday-james** [redisson/redisson-examples#17]
## Description

Run the code snippet in cluster mode, with Spring Boot. Got the following error.
```
java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: c4ba59b1-154e-4e09-926f-010044f547f9 thread-id: 1

	at org.redisson.RedissonLock.lambda$unlockAsync$3(RedissonLock.java:605)
```

## Possible reason
The Lock is acquired and released by the `lock1` object after `t.join` in. `lock.unlock()` line 46 will cause such error as the lock is no longer be acquired by the `lock` object.

## Proposed changes
Remove `lock.unlock()` at line 46, as the lock acquired by the `lock` object is expired automatically after 2 seconds. And `lock1` will release the lock in line 37. The final `unlock` action is redundant and will cause errors.

**Comment by mrniko** [comment]
merged
