### ISSUE TITLE
Any PubSub examples?

### ISSUE THREAD

**Issue by giantninja** [redisson/redisson-examples#2]
I'm looking into possibly replacing my http POST based REST/Api Servlet (that's being used as a mechanism to communicate with my Java application from other non-java applications) with redis PubSub.

Are there any example of how to use Redisson for subscribing/consuming messages that external apps would publish to?

**Comment by jackygurui** [comment]
@giantninja There are lots of tests can be used as examples from the Redisson repo like:
https://github.com/redisson/redisson/blob/master/redisson/src/test/java/org/redisson/RedissonTopicTest.java and https://github.com/redisson/redisson/blob/master/redisson/src/test/java/org/redisson/RedissonTopicPatternTest.java

**Comment by giantninja** [comment]
Ok, thank you for that.  I was looking through the code for something like that, but wasn't looking at the topic/topicpattern stuff.

I did see there was a RedisPubSubConnection and RedisPubSubListener example in the RedisClientTest.java however... what is the difference between the PubSubConnection/PubSubListener vs getTopic()/getPatternTopic() ?

**Comment by jackygurui** [comment]
`getTopic()/getPatternTopic()` give you one of the Topic object and you can then attach a listener to it.

**Comment by giantninja** [comment]
Ok thanks... going to give those a try

**Comment by jackygurui** [comment]
No problem

**Comment by VGerris** [comment]
It would be great if a more concrete example could be provided, for example for a pub sub setup and the best practices for handling communication. The tests are more intended for functional testing and correctness, not to show how to code a production ready program.
