### ISSUE TITLE
Can anyone provide me small Java code to implement redis pipelining ? I am using " redisson-3.2.2.jar" as Redis client

### ISSUE THREAD

**Issue by skjadhav282** [redisson/redisson-examples#4]

**Comment by mrniko** [comment]
Hi! Here is the topic about Redisson pipelining api https://github.com/redisson/redisson/wiki/10.-additional-features#103-execution-batches-of-commands

**Comment by skjadhav282** [comment]
![error1](https://cloud.githubusercontent.com/assets/20432056/23494050/35e8a532-ff36-11e6-8d79-eeddf32f913b.jpg)
Thank you for the Reply.
I have tried that code.
 RBatch batch = redisson.createBatch();
but whenever I type redisson. and ctrl +space in eclipse it doesn't show createBatch() method.

**Comment by mrniko** [comment]
you have to create RedissonClient first, like it shown here https://github.com/redisson/redisson/wiki/2.-Configuration

**Comment by skjadhav282** [comment]
I am connected to the RedissonClient. I have stored some keys through Java code.But still the Same Problem.  **Note: I am using WildFly10 and JDK 7.**

**Comment by skjadhav282** [comment]
public class RedisTestPipeline {
	
	public void testPipeline() throws IOException{
		File w_File = FileUtil.getNewFile("D:/salm/jboss/wildfly10/modules/conf/properties/main/RedisDummy.json");
		Config config = Config.fromJSON(w_File);  
		RedissonClient redisson = Redisson.create(config);
		
		RBatch batch = redisson.createBatch();
		batch.getMap("test").fastPutAsync("1", "2");
        batch.getMap("test").fastPutAsync("2", "3");
        batch.getMap("test").putAsync("2", "5");
      
        RFuture<List<?>> asyncRes = batch.executeAsync();
		
	}

	public static void main(String[] args) {
		RedisTestPipeline  w_Obj = new RedisTestPipeline() ;
	        try
	        {
	        	w_Obj.testPipeline();
	        }
	        
	        catch(RedisConnectionException a_ex)
	        {
	        	
	        	System.out.println("****Redis Connection Exception ******* :- Class Name RedisClient2: -Exception :-" +a_ex.getMessage());
	        }
	        catch(Exception a_ex)
	        {
	        	System.out.println("****Exception ******* :- Class Name RedisClient1: -Exception :-" +a_ex.getMessage());
	        	a_ex.printStackTrace();
	        }
	}

}
// what is "test" in above code? is it predefined Map?
