### ISSUE TITLE
Is There a Way to Retrieve a Hash/Map Along With Its Key?

### ISSUE THREAD

**Issue by HarryTheHawk** [redisson/redisson-examples#6]
Hello,

Is there a means by which one can execute a batch call to retrieve a batch of hashes along with the keys that identify each hash?

For example:

<pre>
key1 -> {"Name" "Tom" "Age" 29}
key2 -> {"Name" "Jerry" "Age" 30}
</pre>

How can one retrieve both the hash and its key (key1, key2, etc.) in the same (batch) request?

**Comment by mrniko** [comment]
Hi,

Use `RMap.readAllMap` it fetches all map data as usual Map object
